### ISSUE TITLE
Problems about zjuthesis

### ISSUE THREAD

**Issue by TheNetAdmin** [Lucas-Wye/Latex_template#1]
repo 里的 zjuthesis 存在一些问题：

1. 建议清理一下 `zjuthesis` 目录下的文件，有些似乎是编辑器生成的临时文件。
2. zjuthesis 里的 Makefile 有问题，只用 xelatex 编译一次是无法全文更新的，比如 reference 就需要用 biber 编译一次才行。建议使用 latexmk，使用方法参见原 repo。
3. zjuthesis 已经更新过很多版本了，但我看这个 repo 里的代码是基于 0.x 版本的，那个版本有很多样式上的错误，后来的版本修复了这些问题，如果有空的话可以更新一下。

**Comment by Lucas-Wye** [comment]
> repo 里的 zjuthesis 存在一些问题：
> 
> 1. 建议清理一下 `zjuthesis` 目录下的文件，有些似乎是编辑器生成的临时文件。
> 2. zjuthesis 里的 Makefile 有问题，只用 xelatex 编译一次是无法全文更新的，比如 reference 就需要用 biber 编译一次才行。建议使用 latexmk，使用方法参见原 repo。
> 3. zjuthesis 已经更新过很多版本了，但我看这个 repo 里的代码是基于 0.x 版本的，那个版本有很多样式上的错误，后来的版本修复了这些问题，如果有空的话可以更新一下。

谢谢提示，已更新原仓库链接并清理相关文件，Makefile已做修改。非常感谢您的建议！

**Comment by TheNetAdmin** [comment]
ok，祝学业顺利
